package main

import (
	"github.com/gin-gonic/gin"
	ginSwagger "github.com/swaggo/gin-swagger"
	_ "github.com/swaggo/gin-swagger/example/basic/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/swaggo/gin-swagger/swaggerFiles"
	"main.go/productCrud/models"
	"main.go/productCrud/routes"
)

func main() {

	db := models.ConnecttoDb()
	db.AutoMigrate(&models.Product{})
	r := routes.RoutersNavigation(db)
	r.Run(":8080")
	rr := gin.New()
	url := ginSwagger.URL("http://localhost:8080/swagger/doc.json")
	rr.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))
	rr.Run(":8080")

}
